# Generated by Django 2.2.5 on 2021-04-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='herohome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('title', models.CharField(max_length=120, verbose_name='Put a Header Title')),
                ('image', models.ImageField(upload_to='site_pics', verbose_name='Image')),
            ],
        ),
    ]
