# Generated by Django 2.2.5 on 2021-04-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, max_length=220)),
                ('skill_name', models.CharField(blank=True, max_length=120)),
                ('percentage', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('heading', models.CharField(max_length=220, null=True)),
                ('description', models.TextField(max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('work_title', models.CharField(max_length=120, null=True)),
                ('wdescription', models.TextField(max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('service_text', models.CharField(blank=True, max_length=120)),
                ('sv_description', models.TextField(blank=True, max_length=220)),
            ],
        ),
    ]
