# Generated by Django 2.2.5 on 2021-04-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0003_client_discount_plan_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herohome',
            old_name='image',
            new_name='hero_image',
        ),
        migrations.AlterField(
            model_name='herohome',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
