# Generated by Django 2.2.5 on 2021-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0004_auto_20210423_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to='portfolio_pics', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='herohome',
            name='hero_image',
            field=models.ImageField(upload_to='portfolio_pics', verbose_name='Image'),
        ),
    ]
