# Generated by Django 2.2.5 on 2021-04-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0005_auto_20210423_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herohome',
            old_name='hero_image',
            new_name='image',
        ),
    ]
