# Generated by Django 2.2.5 on 2021-04-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0006_auto_20210423_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image',
            field=models.ImageField(null=True, upload_to='portfolio_pics', verbose_name='about picture'),
        ),
    ]
