# Generated by Django 2.2.5 on 2021-04-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0007_about_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(upload_to='portfolio_pics', verbose_name='about picture'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=220),
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='about',
            name='percentage',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='about',
            name='skill_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
