# Generated by Django 2.2.5 on 2021-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0009_auto_20210423_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=120)),
                ('percentage', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skill_name',
        ),
    ]
